### ISSUE TITLE
MetFragREST communication test query

### ISSUE THREAD

**Issue by AharoniLab** [ipb-halle/MetFragRelaunched#116]
Hi,

When running the test job on a local 'metfragrest' docker image, I get the following, unknown, error:

`de.ipbhalle.exception.CouldNotCreateProcessException: Could not create process: 'Error: Unknown error'`

Downstream, when running the same POST request from an R environment (using 'httr:POST', the required request body is incompatible with any R data type which I tried: raw text vector, a list or an upload file containing the request body as string as in the example - all return error 415 - unsupported media type.

Can you please expand a bit on how to get this running and which data types (R/Python) can be used or formatted to be used by the API?

**Comment by sneumann** [comment]
Hm, the `unknown error` comes from 
https://github.com/ipb-halle/MetFragRelaunched/blob/9912248ac646541d1f10e4b83df369e4228c369e/MetFragRest/src/main/java/de/ipbhalle/metfragrest/MetFragRestController.java#L110
but no idea about the underlying cause. You can try running in docker as shown in the now updated
https://github.com/ipb-halle/MetFragRelaunched/blob/9912248ac646541d1f10e4b83df369e4228c369e/MetFragRest/README.md

About the R issue: I will investigate. But the demo client works ?
https://github.com/ipb-halle/MetFragRelaunched/blob/9912248ac646541d1f10e4b83df369e4228c369e/MetFragRest/miniclient.sh

Yours,
Steffen

**Comment by AharoniLab** [comment]
The R client runs perfectly with the demo query on the local server.  
I can now go ahead and implement 'MsBackendWeizMass' using this approach - many thanks! 

Could not really get a response from 'http://10.22.13.12:8090/metfrag/api/v1' - is that a public address?

**Comment by sneumann** [comment]
Ah, sorry, my mistake. the 10.x.y.z are IPB Internal. Good you solved it. Once I have figured how to package this in kubernetes, I'd make it public from msbi.ipb-halle.de/something. But we'll have to see if we need rate limiting or something. Not so much on the IPB side, but I wouldn't want that PubChem blocks IPB adresses. Yours, Steffen
