### ISSUE TITLE
Error fetching candidates - HMDB server

### ISSUE THREAD

**Issue by arnau598** [ipb-halle/MetFragRelaunched#140]
Greetings,

3 weeks ago I reported the same error that when I search a mass in the HMDB server it says: error fetching candidates. It had been working well until today when the same error occured. 

![Presentation2](https://github.com/ipb-halle/MetFragRelaunched/assets/167539292/159d317d-aa86-4b3d-801d-a5bbc752ec08)

Thank you for your help!

**Comment by schymane** [comment]
@sneumann are you able to take a look? I can confirm issues with HMDB, but do get candidates from KEGG, PubChem, LipidMaps (well, I got 0 but it is not an error), and even KEGG derivatized (also 0, but no error) with the default query. 
I can get HMDB to respond on Beta, returned 0 candidates with default query, but no error.

**Comment by sneumann** [comment]
Hi, there was one or more unhealthy backend instances, they have been kicked now. Please re-open if still sth is off. Yours, Steffen
