### ISSUE TITLE
Web: currently offline (?)

### ISSUE THREAD

**Issue by chufz** [ipb-halle/MetFragRelaunched#22]
Hi,
we have some issues in our department which reaching the WebServer. Is there some maintenance going on and if yes can you assume how long it will take?

Best Regards
Carolin Huber

**Comment by schymane** [comment]
We've all noticed the same, have been doing (international!) stress testing this week and IPB are working on resolving issues ... someone is running very large queries (>15,000 candidates) and this is stretching the resources to (and beyond) the limits.


We kindly request that users try to keep to queries below a few thousand candidates for the benefit of others (and we are building in a catch to prevent overly large queries pulling the server down). Large queries should be run using the command line interface to avoid this inconvenience for all users.

________________________________

**Comment by chufz** [comment]
Thanks for that information

**Comment by sneumann** [comment]
https://msbi.ipb-halle.de/MetFragBeta/ works for me now. 
Temporarily, you can test drive https://msbi.ipb-halle.de/MetFragK8S/
which will in the future serve as MetFragBeta. Any feedback appreciated. 
Yours, Steffen

**Comment by sneumann** [comment]
Can be closed now, sorry for the inconvenience. Note that the MetFragK8S is not active anymore. Yours, Steffen
