### ISSUE TITLE
Issue retrieving candidates w/ Metfrag Web

### ISSUE THREAD

**Issue by crmclean** [ipb-halle/MetFragRelaunched#32]
Good Afternoon,

I hope this issue finds you well. I was trying to run through the tutorial for metfrag web using the mass of 253.966126 as the neutral mass and kegg as the database. I keep getting an error that reads: "error fetching the candidates". I got the same mistake when I tried with PubChem as the database. Please help!

Craig

**Comment by sneumann** [comment]
Hi, thanks for notifying, we identified the issue and we are on it. 
It might take until tomorrow. Yours, Steffen

**Comment by sneumann** [comment]
Hi, both 
https://msbi.ipb-halle.de/MetFrag/
and
https://msbi.ipb-halle.de/MetFragBeta/
should be running again. Sorry for the inconvenience. 
Yours, Steffen

**Comment by crmclean** [comment]
Thank you kindly for your help. I very much appreciate you taking the time to help me out.

Craig
