### ISSUE TITLE
Arbitrary parent mass limit 1250

### ISSUE THREAD

**Issue by sneumann** [ipb-halle/MetFragRelaunched#43]
We have a report that the web interface limits candidate search 
arbitrarily to 1250, and indeed that is checked in 
https://github.com/ipb-halle/MetFragRelaunched/blob/0e69e62d3c2428367b22bc7bf2c290afe1d8e402/MetFragWeb/src/main/java/de/ipbhalle/metfragweb/controller/MetFragWebBean.java#L551
This could be lifted to mass 2000, but some limit is reasonable 
because larger candidates also increase compute time. 
Yours, Steffeb

**Comment by schymane** [comment]
If you would raise it to 2000 Da, this would cover the ranges of most typical HRMS instruments for small molecules as far as I am aware. While large candidates increase computational time, candidate numbers may be more relevant and (without doing the stats) there are not usually terribly large candidate sets for higher masses?
