### ISSUE TITLE
Local Database order in MetFragWeb

### ISSUE THREAD

**Issue by schymane** [ipb-halle/MetFragRelaunched#79]
@sneumann @meier-rene - any ideas how we can reorder the local database listing in MetFragWeb?
We have old datasets (2018, 2019) coming up at the top ... and exciting new ones disappearing somewhere in the middle. I don't see a logic to the order - it's totally different to what's in the Dockerfile. 

Some are coming from elsewhere ... and it may be worth considering deprecating some of these (but I am not sure where this is located in the code...). Do we have user stats of who is using what databases?

**Comment by meier-rene** [comment]
This request is implemented with bdf9abd5495b9235c9eeae497791851d406ea6e3. You can specify the desired order in the Dockerfile by downloading in reverse order and setting the timestamp of the library files. Please adjust the order if needed.
