### ISSUE TITLE
MetFrag Web issues (no candidates from ChEBI, HMDB)

### ISSUE THREAD

**Issue by schymane** [ipb-halle/MetFragRelaunched#81]
For completeness this was posted in a parallel repo: 
https://github.com/ipb-halle/MetFrag/issues/22

**Comment by schymane** [comment]
Any news on MoNA integration @meier-rene @sneumann ?
Seems most other things are fixed but this is still problematic as far as I'm aware?

**Comment by meier-rene** [comment]
Ok, I think we are done. https://msbi.ipb-halle.de/MetFragBeta/ is running the most recent code. Its version v2.4.8 in the lower left corner.

List of issues we fixed:
- Offline MoNA support was broken
- Fragment viewer had no content
- KEGG outlinks were broken
- database upload dialog was broken
- Command line tool had logging issues
- Command line tool MoNA support was broken
- Candidate retrieval of several databases was broken

Thanks to all reporters. If I missed a problem please open a new issue. I will close this issue.

**Comment by schymane** [comment]
Fabulous - I can confirm MoNA is working again on Beta! Hooray! I tested KEGG and MoNA and all functionality is working as far as I can tell. 
Thanks @meier-rene for all the fixes!
Will test more extensively later and report if I find any other issues. If @sneumann doesn't protest, I would suggest to push to main MetFrag already?

**Comment by sneumann** [comment]
https://msbi.ipb-halle.de/MetFrag/ is now also on `v2.4.8` Yours, Steffen
