### ISSUE TITLE
Submit Feedback is broken

### ISSUE THREAD

**Issue by schymane** [ipb-halle/MetFragRelaunched#85]
This appears to have happened pre-log4j updates ... as it does not appear to work on Feb 2022 or mid-2021 versions of MetFrag. See also https://github.com/ipb-halle/MetFrag/issues/22

**Comment by sneumann** [comment]
Seems to be fixed with c84286945d49690ec3fe164046ac6ed83e45009e (which also closed #88)
In essence, the config file with mail and database settings didn't make it into the container.
