### ISSUE TITLE
log4j2 error

### ISSUE THREAD

**Issue by gilcu3** [ipb-halle/MetFragRelaunched#86]
This error is generated every time I run the command line jar.
I am using java11-jdk, metfrag-2.4.6, on linux.

```
standard error output:
ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
```
I think it may be solved by adding the log4j2 dependency to the required pom.xml.

This issue was hiding the reason for an error, for example when the parameter `MaxCandidateLimitToStop` was too low, the output is just:
```
ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
java.lang.Exception
	at de.ipbhalle.metfrag.commandline.CommandLineTool.main(CommandLineTool.java:105)
ERROR CommandLineTool Error when retrieving compounds.

```
as opposed to the output when using metfrag-2.4.5 and java8-jdk:
```
INFO  de.ipbhalle.metfraglib.process.CombinedMetFragProcess - 130 candidate(s) exceeds the defined limit (MaxCandidateLimitToStop = 100)
java.lang.Exception
	at de.ipbhalle.metfrag.commandline.CommandLineTool.main(CommandLineTool.java:105)
ERROR de.ipbhalle.metfrag.commandline.CommandLineTool - Error when retrieving compounds.
```

**Comment by meier-rene** [comment]
Thanks for reporting. I'm investigating this atm. 

The following is just a reference for myself: When I add the dependency, I run into this problem: https://issues.apache.org/jira/browse/LOG4J2-954

**Comment by meier-rene** [comment]
I think its solved now. I would appreciate some feedback if its also the case on your system. I have prepared a new release, which you can download from the release section.

**Comment by gilcu3** [comment]
The error is shown correctly now. Still, now using java-11 or java-17 (java-8 is not compatible, what is the supported java version btw?) I get a warning related to reflection:
```
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
14:37:38.361 INFO  de.ipbhalle.metfraglib.process.CombinedMetFragProcess - 130 candidate(s) exceeds the defined limit (MaxCandidateLimitToStop = 100)
java.lang.Exception
	at de.ipbhalle.metfrag.commandline.CommandLineTool.main(CommandLineTool.java:105)
14:37:38.364 ERROR HelloWorld - Error when retrieving compounds.
```

**Comment by meier-rene** [comment]
I develop, test and use java-11. I don't know how it works with 17 or 8, but I do not test at the moment on this versions. I would hope that it runs on 17. 

The reflection WARNING can be ignored. Maybe I'll finfd asolution for this in the future.
