### ISSUE TITLE
CSV Upload broken in MetFragWeb

### ISSUE THREAD

**Issue by schymane** [ipb-halle/MetFragRelaunched#89]
If I try to upload a CSV file in the current https://msbi.ipb-halle.de/MetFrag/ it shows a brief sign of life and then just "disappears"  - but uploads fine in older versions (pre-updates)

This is "post upload" on v2.4.6
![image](https://user-images.githubusercontent.com/4070141/156715797-5117d8a2-367e-4c99-ae4b-94c0bd4e4162.png)

But on an earlier version (v2.1) with same file: 
![image](https://user-images.githubusercontent.com/4070141/156715861-63ffc777-321f-45fa-a1d3-af777f585009.png)

**Comment by meier-rene** [comment]
We have rolled out a updates version. It can be identified by 2.4.7 in the lower left corner. This version should fix this issue. Could you please check?

**Comment by schymane** [comment]
Yes, confirm it works with this file: 
![image](https://user-images.githubusercontent.com/4070141/157489695-da17c137-9d20-4703-b33c-c09ea9c27d77.png)

on this version: 
![image](https://user-images.githubusercontent.com/4070141/157489750-df672627-68c0-4406-9b74-50e07c7ac86b.png)

Thanks! ;-)
