### ISSUE TITLE
different OfflineMetFusionScore values

### ISSUE THREAD

**Issue by gilcu3** [ipb-halle/MetFragRelaunched#90]
Environment:
Linux java-11-jdk

parameters file: [parameters34cb6d1cb2af2f.txt](https://github.com/ipb-halle/MetFragRelaunched/files/8215915/parameters34cb6d1cb2af2f.txt)
spectrum file: [spectrum34cb6d3ae3d66b.txt](https://github.com/ipb-halle/MetFragRelaunched/files/8215932/spectrum34cb6d3ae3d66b.txt)
local database: [PubChemLite_31Oct2020_exposomics](https://zenodo.org/record/4183801)

With metfragCL 2.4.5 the output is: [results34cb6d196b0dd-metfrag2.4.5.csv](https://github.com/ipb-halle/MetFragRelaunched/files/8215934/results34cb6d196b0dd-metfrag2.4.5.csv)
With metfragCL 2.4.7 the output is: [results34cb6d196b0dd-metfrag2.4.7.csv](https://github.com/ipb-halle/MetFragRelaunched/files/8215937/results34cb6d196b0dd-metfrag2.4.7.csv)

Using version 2.4.7 the column OfflineMetFusionScore is filled with 0s, while it should not be, at least according to version 2.4.5.

I got the same problem for column OfflineIndividualMoNAScore in another experiment.

**Comment by schymane** [comment]
Likely related to the MoNA parts of https://github.com/ipb-halle/MetFrag/issues/22 - MoNA is also broken on the newer web versions...

**Comment by sneumann** [comment]
We might have found the culprit in https://github.com/ipb-halle/MetFragRelaunched/commit/1a26a9ac29322525e2f72016af327a3915905032 and @meier-rene  is on it to fix. A continuous integration performance regression test by @c-ruttkies is in the works to catch things like this. Yours, Steffen

**Comment by schymane** [comment]
OK great, because we still have our "back-up" running (as we need it atm), but it costs $$$ every day to keep running ... ;-)

**Comment by meier-rene** [comment]
Fixed and checked or identical results. Thank @gilcu3 for your detailed report with example to test. I will release a new version 2.4.8 which includes this fix.
